apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: shahdabdulaziz/to-do-list-app
    argocd-image-updater.argoproj.io/shahdabdulaziz/to-do-list-app.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/ShahdMenaisy/ToDoList-App.git
    targetRevision: main
    path: k8s_manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: todolist
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
