---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: todolist
  labels:
    app: todolistapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolistapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: todolistapp
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: app-container
        image: shahdabdulaziz/to-do-list-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: mongoDbUrl
          value: "mongodb://mongodb-svc:27017/todo"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: todolist
spec:
  selector:
    app: todolistapp
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 32002
  type: NodePort
